language: rust
rust:
  - 1.15.0
  - stable
  - beta
  - nightly
env:
  matrix:
    - # no features
    - FEATURES="full-syntax"

matrix:
  include:
    # try a no-std target
    - rust: stable
      env: TARGET=thumbv6m-none-eabi
      before_script:
        - rustup target add "$TARGET"
      script:
        # This test crate is intentionally separate, because we need
        # independent features for no-std. (rust-lang/cargo#2589)
        - cd check && cargo check --target "$TARGET"

sudo: false
script:
  - cargo build --verbose --features="$FEATURES"
  - ./ci/test_full.sh
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - next
    - staging
    - trying
