language: rust
sudo: false
rust:
  - 1.31.0 # 2018!
  - stable
  - beta
  - nightly
env:
  matrix:
    - # no features
    - FEATURES="full-syntax"
script:
  - cargo build --verbose --features="$FEATURES"
  - ./ci/test_full.sh

matrix:
  include:
    # try a no-std target
    - name: "no_std"
      rust: stable
      env: TARGET=thumbv6m-none-eabi
      before_script:
        - rustup target add "$TARGET"
      script:
        # This test crate is intentionally separate, because we need
        # independent features for no-std. (rust-lang/cargo#2589)
        - cd check && cargo check --target "$TARGET"

    - name: "rustfmt"
      rust: 1.31.0
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - next
    - staging
    - trying
