[package]
authors = ["The Rust Project Developers"]
description = "Numeric syntax extensions"
documentation = "https://docs.rs/num-derive"
homepage = "https://github.com/rust-num/num-derive"
keywords = ["mathematics", "numerics"]
categories = [ "science" ]
license = "MIT/Apache-2.0"
name = "num-derive"
repository = "https://github.com/rust-num/num-derive"
version = "0.1.41"
readme = "README.md"

[dependencies]
proc-macro2 = "0.2.1"
quote = "0.4.2"

[dependencies.syn]
version = "0.12.7"
features = ["full"]

[dev-dependencies]
compiletest_rs = "0.3.5"

[dev-dependencies.num]
version = "0.1"

[lib]
name = "num_derive"
proc-macro = true
test = false
