[package]
authors = ["The Rust Project Developers"]
description = "Numeric syntax extensions"
documentation = "https://docs.rs/num-derive"
homepage = "https://github.com/rust-num/num-derive"
keywords = ["mathematics", "numerics"]
categories = [ "science" ]
license = "MIT/Apache-2.0"
name = "num-derive"
repository = "https://github.com/rust-num/num-derive"
version = "0.1.42"
readme = "README.md"

[dependencies]
proc-macro2 = "0.2.1"
quote = "0.4.2"
syn = "0.12.7"

[dev-dependencies]
compiletest_rs = "0.3.5"

[dev-dependencies.num]
version = "0.1"

[dev-dependencies.num-derive]
path = "."
features = ["full-syntax"]

[features]
full-syntax = ["syn/full"]

[lib]
name = "num_derive"
proc-macro = true
test = false
