[package]
authors = ["The Rust Project Developers"]
description = "Numeric syntax extensions"
documentation = "https://docs.rs/num-derive"
homepage = "https://github.com/rust-num/num-derive"
keywords = ["mathematics", "numerics"]
categories = [ "science" ]
license = "MIT/Apache-2.0"
name = "num-derive"
repository = "https://github.com/rust-num/num-derive"
version = "0.2.0"
readme = "README.md"

[dependencies]
num-traits = "0.2"
proc-macro2 = "0.3.8"
quote = "0.5.2"
syn = "0.13.7"

[dev-dependencies]
num = "0.1"

[features]
full-syntax = ["syn/full"]

[lib]
name = "num_derive"
proc-macro = true
test = false
